### ISSUE TITLE
No Colors on folders

### ISSUE THREAD

**Issue by YamatoSOA** [CyanVoxel/Obsidian-Colored-Sidebar#19]
I'm not really sure if it's an issue, but I assume that downloading and putting in my css folder and activating it would make my folders have colors and stuff like previewed, but when I tried, I get only bold text folders and nothing else on both light and dark theme. I tried messing with my current plugins, turning them off to see if any changes, and nothing still... I even tried just using 
![Obsidian_USyoqWdZSc](https://github.com/user-attachments/assets/8b6de647-c91b-4f26-a441-8366c1a217f2)
![Obsidian_aOil61AU4E](https://github.com/user-attachments/assets/d370aee2-1947-4681-ab11-041a1d60146b)

**Comment by CyanVoxel** [comment]
Hmm, are you absolutely *sure* that there aren't any other themes or snippets interfering here? And you're not on a *very* old version of Obsidian?

**Comment by YamatoSOA** [comment]
Nevermind. Apparently the code is only bold... sorry for causing worry...

I just notice that the prefix below is something that I have to copy to the main thing and not something that are already linked to the functioning code or something. Now I'm gonna figure out how to make them appears in rainbow colors.

Again, sorry for submitting false issue. It's my fault on my end
