### ISSUE TITLE
How do I set this up? Missing documentation

### ISSUE THREAD

**Issue by Max-Jesch** [CyanVoxel/Obsidian-Colored-Sidebar#2]
Would be nice if you could add some explanation on what to actually do with this :-P

**Comment by prolenodev** [comment]
I came from the nice [YouTube video](https://www.youtube.com/watch?v=rAkerV8rlow) you uploaded, thank you!
A documentation on this point will be helpful, but for the meantime I want to add this comment for those who are just as confused as I was at first.

After I placed the css file `Colored Sidebar Items.css` in `\.obsidian\snippets` folder, then turned on the toggle on Settings>Appearance>CSS Snippets, I was at first confused why it did not work. I thought my other CSS snippets clashed with this one somehow.

Thanks to your [example vault](https://github.com/CyanVoxel/Obsidian-Vault-Template), I noticed I had to rename the folders by appending '01 - Folder Name' or '02 - Folder Name'.

To use just 'Folder Name', change `[data-path^="07"]`  to `[data-path^="Folder Name"]`.

To add more colours after the 7th colour, edit the CSS file to add in the lines for the 8th colour.
	- change `--hot-red: #e3365e;            /* Default Prefix: 07 */` to `--cool-gray: #515768;             /* Default Prefix: 08 */`
	- change `[data-path^="07"]` to `[data-path^="08"]`
	- change `var(--hot-red)` to `var(--cool-gray)`

This is the part from the code I am referring to:

```
/* ------------------------------- 08 Prefix -------------------------------- */
.nav-folder-title[data-path^="08"] {
  color: var(--cool-gray);
  --nav-item-color-hover: color-mix(
    in srgb,
    var(--cool-gray) var(--fg-contrast-amount),
    var(--contrast-color)
  );
  --nav-item-background-hover: color-mix(
    in srgb,
    var(--cool-gray) var(--bg-contrast-amount),
    transparent
  );
  --background-modifier-border-focus: color-mix(
    in srgb,
    var(--cool-gray) 40%,
    transparent
  );
  --nav-collapse-icon-color: color-mix(
    in srgb,
    var(--cool-gray) 60%,
    transparent
  );
}
.nav-folder-title[data-path^="08"]:hover {
  --nav-collapse-icon-color: color-mix(
    in srgb,
    var(--cool-gray) 60%,
    var(--contrast-color)
  );
}
.tree-item-children .nav-folder:has(.nav-folder-title[data-path^="99"]) {
  --nav-indentation-guide-color: color-mix(
    in srgb,
    var(--cool-gray) var(--medium-contrast-amount),
    transparent
  );
}
.tree-item-children
  .nav-folder:has(.nav-folder-title[data-path^="99"])
  .nav-file-title {
  color: color-mix(
    in srgb,
    var(--cool-gray) var(--medium-contrast-amount),
    var(--default-text-color)
  );
  --nav-item-background-hover: color-mix(
    in srgb,
    color-mix(in srgb, var(--cool-gray) 50%, var(--highlight))
      var(--bg-contrast-amount),
    transparent
  );
  --background-modifier-border-focus: color-mix(
    in srgb,
    var(--cool-gray) 40%,
    transparent
  );
  --nav-item-background-active: color-mix(
    in srgb,
    var(--cool-gray) var(--active-contrast-amount),
    transparent
  );
}
```

**Comment by CyanVoxel** [comment]
Hey there! Yes I'm sorry, I know the whole prefix process went pretty unexplained by me and I'll definitely add better documentation to help explain it for newcomers! (I never expected these repos to get the traffic they've gotten, so I'm going around adding better documentation + instructions independent from the videos as well!)

**Comment by prolenodev** [comment]
Please don't feel the need to apologise for the time and effort you dedicated to producing such great work. Thank you very much for sharing it!

**Comment by CyanVoxel** [comment]
Just added some new installation + usage documentation in 497feba5f2e680bdb9b37aa1cd14d4eff178931e! Thank you all for taking the time to write and check out the snippet!
