### ISSUE TITLE
Install Colored Sidebar Items.css problem

### ISSUE THREAD

**Issue by EvgenA** [CyanVoxel/Obsidian-Colored-Sidebar#3]
I was impressed by your video. Above all, to start with the design👍👍👍
But the problem, for novices like me in Obsidian, turns out to be more complicated than I thought.
After downloading and installing the Colored Sidebar-Items.css file in the snippets folder and enabling it in Obsidian settings.... nothing happens🤔 Did I miss something during installation or configuration?
I even downloaded the Vanilla AMOLED theme, but nothing changes.
I would be really grateful to you 🙏 if you added the steps to follow, in your next videos, for people like me, who have the opinion of diving into the world of Obsidian.
Good luck with your tutorials, which attract a lot of attention.

<img width="773" alt="1" src="https://github.com/CyanVoxel/Obsidian-Colored-Sidebar/assets/19775987/10b7fc9b-3db5-443f-8f04-fa0e34c96310">

**Comment by CyanVoxel** [comment]
Sorry about the lack of documentation! I've just added new installation + usage instructions in commit 497feba5f2e680bdb9b37aa1cd14d4eff178931e. Hopefully that clears things up!

**Comment by EvgenA** [comment]
Thank you so much Travis 👍
We learn every day 🙄 The novices would be really grateful to you for this gesture.
As for me, I'm already impatient 🤞
Have a nice week-end.

---------------

**Comment by EvgenA** [comment]
Travis, currently I'm using the Blue Topaz theme and I'm very fond of it.
This may seem like a naive question, but I'll ask it anyway; your plugin is only compatible with Vanilla AMOLED theme??! Since, for my part, it still doesn't do anything.
Sorry, but I'm still counting on your response.
Maybe a little video tutorial for Dummies 🤗🙏?
Have a nice week-end.

￼

**Comment by EvgenA** [comment]
PS. Just in case, if you didn't receive my previous capture:

￼

-----------------

**Comment by EvgenA** [comment]
Hi Travis,

I'm coming back to you, late, just to tell you that I found the answer to my questions in my previous message 🤩
I'm letting you know, just so you can save your time just in case.

--------------
